### ISSUE TITLE
default value setting doesnt work for combobox

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/rgg#3]
I dont know if it should work, on e.g. textbox and checkbox the default setting work, but on combobox they dont.

colName = <combobox items="$$$ALL_ATTRIBUTES$$$" label="Column" default-value="plateColumn"/>;

no error, but default value is ignored.

(Martin)

**Comment by stoeter** [comment]
This is not a bug. Default does not exist for combobox. See documentation [http://rgg.r-forge.r-project.org/docs.html] chapter 6.3
Instead the key word "selected-item" with the default item or "selected-index" can be used, where the given number is the default value given as position in given list (items).

The issue can be closed.
